### ISSUE TITLE
Fix "?&s=" across all libraries

### ISSUE THREAD

**Issue by kellysutton** [imgix/imgix-blueprint#2]
Many libraries, [like the Ruby library](https://github.com/imgix/imgix-rb#domain-sharded-urls), generate invalid URLs for signed imgix API URLs where the images are passed-through, i.e. the signature is the only URL parameter.

**Expected result:** All libraries should properly build and sign URLs without other parameters.

All instances of

```
?&s=…
```

should become

```
?s=…
```

**Note:** This will change the value of all signatures.

**Comment by sherwinski** [comment]
Closing as this is no longer an issue in our official libraries.
