### ISSUE TITLE
Update list of available libraries

### ISSUE THREAD

**Issue by paulstraw** [imgix/imgix-blueprint#9]
The list in this repo is currently pretty out of date compared to [the site docs](https://www.imgix.com/docs/libraries). Just going to update to match.

**Comment by paulstraw** [comment]
Looking at this, it seems like at least mentioning that the framework libraries exist under the "Existing Libraries" section would be a good idea. Right now, it kind of seems like there aren't any.

I'm thinking just a simple sentence with a link to the [docs page](https://www.imgix.com/docs/libraries). @kellysutton, you cool with that?

**Comment by kellysutton** [comment]
I think that's a good idea. :+1:
